[[pages]]
path = "streamlit_app.py"
name = "é¦–é¡µ"
icon = "ğŸ "

[[pages]]
path = "pages/workbench/create.py"
name = "åˆ›å»º"
icon = "ğŸª„"

[[pages]]
path = "pages/workbench/search.py"
name = "æœç´¢"
icon = "ğŸ”"


[[pages]]
path = "pages/analysis/visualize.py"
name = "å¯è§†åŒ–"
icon = "ğŸ“Š"

[[pages]]
path = "pages/user_manage/user_manage.py"
name = "ç”¨æˆ·ç®¡ç†"
icon = "ğŸ§‘â€ğŸ¤â€ğŸ§‘"

[[pages]]
path = "./pages/auth/reset_password.py"
name = "ä¿®æ”¹å¯†ç "
icon = ""