[[pages]]
path = "streamlit_app.py"
name = "é¦–é¡µ"
icon = "ğŸ "

[[pages]]
path = "./pages/auth/register.py"
name = "æ³¨å†Œ"
icon = ""

[[pages]]
path = "./pages/auth/forget_password.py"
name = "å¿˜è®°å¯†ç "
icon = ""

[[pages]]
path = "./pages/auth/forget_username.py"
name = "å¿˜è®°ç”¨æˆ·å"
icon = ""
